job/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name='job'
urlpatterns = [

    path('', views.job_list,name='all_jobs'),
    path('add/', views.add_job,name='add_job'),
    
    path('<int:id>', views.job_detail,name='job_detail'),
]

project_jops/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
       path('accounts/', include('django.contrib.auth.urls')),
       path('accounts/', include('accounts.urls',namespace='accounts_p'),),

    path('admin/', admin.site.urls),
    path('', include('job.urls',namespace='jobs')),
    path('contact/',include('contact.urls',namespace='contact')),
    path('',include('tests.urls',namespace='test_')),
    path('',include('patient.urls',namespace='patient')),
    path('',include('c_b_v.urls',namespace='c_b_v')),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import User

JOB_TYPE=(
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
 )
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)  
    
    def __str__(self):
        return self.name  

class Job(models.Model):
    owner=models.ForeignKey(User,on_delete=models.CASCADE,related_name='job_owner')
    title=models.CharField(max_length=50)
    job_type=models.CharField(max_length=15,choices=JOB_TYPE)
    description=models.TextField(max_length=1000)
    published_at=models.DateTimeField(auto_now=True)
    Vacancy=models.IntegerField(default=1)
    salary=models.IntegerField(default=0)
    experience=models.IntegerField(default=1)
    category=models.ForeignKey(Category,related_name='job_catogrey',on_delete=models.CASCADE)
    image=models.ImageField(upload_to='image/jops/')


    def __str__(self):
        return self.title


class Apply(models.Model):
    job=models.ForeignKey(Job,related_name='apply_job',on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    website=models.URLField()
    cv=models.FileField(upload_to='apply/')
    cover_latter=models.TextField(max_length=500)
    create_at=models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

job/views.py
from django.shortcuts import redirect, render
from .models import  Job
from django.core.paginator import Paginator
from .form import ApplyForm,Job_add_form
from .filters import JobFilter
# Create your views here.

def job_list(request):
    job_list=Job.objects.all()  

    myfilter=JobFilter(request.GET,queryset=job_list)
    job_list=myfilter.qs



    paginator=Paginator(job_list,3)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)

    

    context={ 'all_job':page_obj,'myfilter':myfilter}
    return render(request,'jobs.html',context)

class Meta:
   ordering = ['-id']


def job_detail(request,id):
    job_id=Job.objects.get(id=id)
    if request.method=='POST':
        form=ApplyForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.job=job_id
            myform.save()
    else:
        form=ApplyForm()
    x={ 'job':job_id,'form':form}
    return render(request,'job-details.html',x)

class Meta:
   ordering = ['id']



def add_job(request):
    #job_id=Job.objects.get(id=id)
    if request.method=='POST':
        form=Job_add_form(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.owner=request.user
            myform.save()
        
        return redirect('jobs:add_job')
    else:
        form=Job_add_form()
        j=Job.objects.all()
    x={ 'form':form, 'j':j}
    return render(request,'job-add.html',x)




   

job/templates/job-add.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block page_title  %}
<h2>
    ADD NEW JOB
</h2>
{% endblock %}
{% block body %}


<!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-md-9  col-sm-8">
          <div class="text-content">
            
          
            <form method="POST" enctype="multipart/form-data" >

                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" class="btn btn-primary">Save</button>

                {% endbuttons %}


            </form>
          </div>
        </div>
      </div>
   
  </div>


{% for c in j  %}

{{c.title}}
{% endfor %}

  {% endblock %}

job/templates/job-details.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}
{% block page_title  %}
<h2>
    {{job}}
</h2>
{% endblock %}
{% block body %}


<div class="products">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-sm-8">
          <p class="lead">
               <i class="fa fa-map-marker"></i> London &nbsp;&nbsp;
               <i class="fa fa-calendar"></i> {{job.published_at | date:"d-m-Y"}} &nbsp;&nbsp;
               <i class="fa fa-file"></i> Contract
          </p>

          <br>
          <br>
          
          <div class="form-group">
            <h5>Decription</h5>
          </div>
          <br>
         <p>
          {{job.description}}
         </p>
          <br>
      </div>

      <div class="col-md-3 col-sm-4">
        <div class="contact-form">
          <div class="form-group">
            <button type="submit" class="filled-button btn-block">Apply for this job</button>
          </div>
        </div>

        <div>
          <img src=" {{job.image.url}} " alt="kljljk" class="img-fluid wc-image">
        </div>

        <br>

        <ul class="social-icons text-center">
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-envelope"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-behance"></i></a></li>
        </ul>

        <br>
        <br>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        <div class="section-heading">
        </div>

       <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {% bootstrap_form form %}

                  

       <div class="contact-form">
        
          <button type="submit" class="filled-button btn-block">Apply for this job</button>
        </form>
      </div>
      </div>

      <div class="col-md-3">
        <div class="section-heading">
          <h2>Contact Details</h2>
        </div>
        
        <div class="left-content">
          <p>
            <span>Name</span>

            <br>

            <strong>John Smith</strong>
          </p>

          <p>
            <span>Phone</span>

            <br>
            
            <strong>
              <a href="tel:123-456-789">123-456-789</a>
            </strong>
          </p>

          <p>
            <span>Mobile phone</span>

            <br>
            
            <strong>
              <a href="tel:456789123">456789123</a>
            </strong>
          </p>

          <p>
            <span>Email</span>

            <br>
            
            <strong>
              <a href="mailto:john@carsales.com">john@carsales.com</a>
            </strong>
          </p>

          <p>
            <span>Website</span>

            <br>
            
            <strong>
              <a href="http://www.cannonguards.com/">http://www.cannonguards.com/</a>
            </strong>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

job/templates/jobs.html
{% extends "base.html"%}
{% load bootstrap4 %}
{% block page_title %}
<h2>
     Jobs Avilable
</h2>
{% endblock %}
{% block body %}

<div class="products">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
         <div class="contact-form">
           <form method="get">
{% bootstrap_form myfilter.form %}
<input type="submit">
           </form>
         </div>
      </div>

      <div class="col-md-9">
        <div class="row">
          {% for x in all_job %}
          <div class="col-md-6">
            
            <div class="product-item">
              <a href="{% url  'jobs:job_detail' x.id  %}"><img src="  {{x.image.url}}  " alt="image" ></a>
              <div class="down-content">
                <a href="{% url  'jobs:job_detail' x.id  %}"><h4>{{x.title}}</h4></a>
      
                <h6>{{x.salary}}</h6>
      
                <h4><small><i class="fa fa-briefcase"></i> Medical / {{x.category}} <br> <strong><i class="fa fa-building"></i> BMI Kings Park Hospital</strong></small></h4>
      
                <small>
                     <strong title="Posted on"><i class="fa fa-calendar"></i> {{x.published_at | date:"d-m-Y"}}</strong> &nbsp;&nbsp;&nbsp;&nbsp;
                     <strong title="Type"><i class="fa fa-file"></i> Contract</strong> &nbsp;&nbsp;&nbsp;&nbsp;
                     <strong title="Location"><i class="fa fa-map-marker"></i> London</strong>
                </small>
              </div>
            
            </div>
            
          </div>
          {% endfor %}
         
        
          {% if all_job.has_other_pages %}
          <div class="col-md-12">
            <ul class="pages">
              {% if all_job.has_previous %}
              <li><a href="?page={{all_job.previous_page_number}} "><i class="fa fa-angle-double-left"></i></a></li>
              {% endif %}
      
              {% for i in all_job.paginator.page_range %}
              
      
                <li class="{% if i   == all_job.number %} active {% endif %}" ><a href="?page={{i}}">{{i}}</a></li>
              
           
      
              {% endfor %}
      
              
      
      
              {% if all_job.has_next %}
              <li><a href="?page={{all_job.next_page_number}}"><i class="fa fa-angle-double-right"></i></a></li>
              {% endif %}
            </ul>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

{%  endblock %}